# Generated by Django 5.1.7 on 2025-04-06 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Airline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("year_founded", models.DateField()),
                ("outside_of_europe", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Baloon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("S", "Small Baloon"),
                            ("M", "Medium Baloon"),
                            ("L", "Large Baloon"),
                        ],
                        max_length=1,
                    ),
                ),
                ("distributed", models.CharField(max_length=100)),
                ("num_of_passengers", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Pilot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "hours_of_flight",
                    models.DecimalField(decimal_places=2, max_digits=3),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("J", "Junior"),
                            ("I", "Intermediate"),
                            ("S", "Senior"),
                        ],
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("airport_takeoff", models.CharField(max_length=100)),
                ("airport_landing", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="images/")),
                ("date", models.DateField()),
                (
                    "airline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flight2.airline",
                    ),
                ),
                (
                    "baloon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="flight2.baloon"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pilot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="flight2.pilot"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AirlinePilot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "airline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flight2.airline",
                    ),
                ),
                (
                    "pilot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="flight2.pilot"
                    ),
                ),
            ],
        ),
    ]
